### ISSUE TITLE
Undefined result for certain base urls

### ISSUE THREAD

**Issue by krsyoung** [ErikWittern/is-base-url#1]
Certain base URLs seem to cause an error when calling the library.  For example, a base url of `https://servicehost/oauth).` results in `undefined` being returned.

**Comment by ErikWittern** [comment]
This is actually intended behavior: the function returns `undefined` if the given variable is not a string _or_ is not a valid url.

**Comment by krsyoung** [comment]
Curious, why not return -1 in this case?  Or how would -1 differ from `undefined`?

**Comment by ErikWittern** [comment]
When passing a non-string, the feature extraction would likely fail, resulting in errors. When passing strings which are not valid URLs, that's not a problem. In that case, however, I think returning -1 would be misleading because this score would not be based on the features any more. Another option would be to only pass the score and not the features in that case. However, then the application needs to handle cases where the score is -1 and no features exist. I believe its cleaner to just check whether a result is returned at all.

Also, since version 1.1.0, it is possible to send a `checkValidUrl` option if you don't want to check for URL validity.

**Comment by krsyoung** [comment]
Perfect, makes sense!  So `undefined` = impossible to score.  Makes sense.  Great library!
